#' Produce a skyline plot starting from a BDMM-prime MCMC log
#'
#' This function deals with parameters that change over time within each deme
#' (e.g. R0, s), not between demes (e.g. migration R0AmongDemes).
#'
#' It returns a ggplot with overimposed (with transparency) plot colour-coded
#' for each deme. This can be edited post-production as usual for
#' ggplot-objects. For example, if multiple plots - one for each deme - are
#' needed, this can be easily achieved with \code{facet_grid} (say the plot generated by \code{make.BDMMbydeme.skyplot} is p, you could use :
#' \code{p + facet_grid(Deme~.)} to have each deme on separate rows).
#'
#' @param par the parameter to be plotted. Possible option: "R0", "s" (sampling
#'   proportion), "delta" (becomingUninfectiousRate), "r" (removevalProbability)
#' @param nBins the number of bins to use (integer of length=1)
#' @param type The type of plot to generate. This will depend on how the
#'   analysis has been set up: "smooth" if the timeChanges parameters are
#'   estimated; "step" is these are fixed.
#' @inheritParams make.epochs.data
#' @inheritParams extract.HPD
#' @import data.table
#' @import ggplot2
#' @importFrom boa boa.hpd
#' @export
#'
make.BDMMbyDeme.skyplot <- function(log, par=c("R0", "s", "delta", "r"), nBins=100,
                                    type=c("smooth", "step"), alpha=0.05, maxAge) {
    param <- match.arg(par)
    switch(param, R0=param <- "R0SVEpi", s=param <- "samplingProportionSVEpi",
           delta=param <- "becomeUninfectiousRateSVEpi", r=param <- "removalProbSVEpi")
    type <- match.arg(type)

    dat <- log[, grep(param, names(log)), with=FALSE]

    # matches <- regexec("i[0-9]+_", names(dat))
    # starts <- sapply(matches, attr, "match.length") + 1
    # demes <- substring(names(dat), starts)

    demes <- sapply(strsplit(names(dat), "_"), tail, 1)
    demes <- unique(demes[grep("endtime", demes, invert = TRUE)])
    nDemes <- length(demes)
    dat_demes <- lapply(demes, extract.cols, dt=dat)
    endtimes <- as.matrix(dat[, grep("endtime", names(dat)), with=FALSE])
    origCol <- grep(names(log), pattern = "originBDMMPrime")
    origins <- log[[origCol]]

    hpd <- vector("list", length = nDemes)
    if(type == "smooth") {
        parByGrid_demes <- vector("list", length = nDemes)
        for(d in seq_len(nDemes)) {
            parByGrid_demes[[d]] <- matrix(nrow = nrow(endtimes), ncol = nBins)
        }
        for(d in seq_len(nDemes)) {
            for(rn in seq_len(nrow(endtimes))) {
                x <- seq(0, origins[rn],  length.out = nBins)
                br <- c(0, endtimes[rn,], origins[rn])
                parByGrid_demes[[d]][rn, ] <- as.numeric(dat_demes[[d]][rn,
                                                                        .bincode(x, br, TRUE, TRUE),
                                                                        with=FALSE])

            }
        }

        hpd1col <- vector("list", length = nDemes)
        medians <- vector("list", length = nDemes)
        for(d in seq_len(nDemes)) {
            hpd[[d]] <- apply(parByGrid_demes[[d]], 2, boa::boa.hpd, alpha = alpha)
            hpd[[d]] <- t(hpd[[d]])
            hpd1col[[d]] <- c(hpd[[d]][, 1], rev(hpd[[d]][,2]))
            medians[[d]] <- c(apply(parByGrid_demes[[d]], 2, median), rev(apply(parByGrid_demes[[d]], 2, median)))
        }
        hpd1col <- lapply(hpd1col, data.table)
        names(hpd1col) <- demes
        hpd1col <- rbindlist(hpd1col, idcol = "Deme")
        hpd1col[, Median := do.call(c, medians)]
        setnames(hpd1col, "V1", "Param")
        times <- seq(0, median(origins),  length.out = nBins)
        ages <- maxAge - median(origins) + times
        hpd1col[, Times := rep(c(times, rev(times)), 4)]
        hpd1col[, Age := rep(c(ages, rev(ages)), 4)]
        skyplot <- ggplot(hpd1col, aes(x = Age, y=Param, col=Deme, fill=Deme)) +
            geom_polygon(alpha=0.5) +
            geom_line(aes(Age, Median)) #+ facet_grid(Deme~.)
    } else {
        epochs <- vector("list", length = nDemes)
        for(d in seq_len(nDemes)) {
            hpd[[d]] <- extract.HPD(dat_demes[[d]], alpha = alpha)
            epochs[[d]] <- make.epochs.data(hpd[[d]], maxAge = maxAge,
                                            gridPoints = median(origins) - apply(endtimes, 2, median),
                                            rootHeight = median(origins))
            epochs[[d]][, Deme :=rep(demes[d], nrow(epochs[[d]]))]
        }
        skyplot <- make.skyplot(epochs, by = "Deme") #+ facet_grid(Deme~.)
    }
    return(skyplot)
}
